pitch_deck/generator/urls.py
from django.urls import path

from . import views

app_name = 'generator'

urlpatterns = [
    path('pitch-deck', views.pitch_deck, name='pitch-deck'),
    path('', views.index, name='index'),
]

pitch_deck/pitch_deck/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('generator.urls',
                     namespace='generator')),
]

pitch_deck/generator/forms.py
from django import forms


class PitchDeckForm(forms.Form):
    name = forms.CharField(
        label='Название', max_length=100,
        required=True
    )
    problem = forms.CharField(
        label='Проблема',
        widget=forms.Textarea(attrs={'rows': '2'}),
        required=True
    )
    description = forms.CharField(
        label='Описание',
        widget=forms.Textarea(attrs={'rows': '3'}),
        required=True
    )
    solution = forms.CharField(
        label='Решение',
        widget=forms.Textarea(attrs={'rows': '3'}),
        required=True
    )
    market_size = forms.CharField(
        label='Размер рынка',
        required=False
    )
    market = forms.CharField(
        label='Рынок',
        required=True,
        help_text='На каком рынке вы себя позиционируете (Hardware, IndustrialTech и.т.д)?'
    )
    okved = forms.CharField(
        label='ОКВЕД',
        required=True
    )
    region = forms.CharField(
        label='Регион, в котором вы развиваете бизнес',
        required=True
    )
    percentage_of_som_from_sam = forms.DecimalField(
        label='Процент SOM от SAM',
        help_text='Укажите значение в процентах от 0 до 1',
        required=True
    )
    bm_consumer_segments = forms.CharField(
        label='Потребительские сегменты',
        widget=forms.Textarea(attrs={'rows': '2'}),
        help_text='Кто у нас покупает?',
        required=True
    )
    bm_consumer_problem = forms.CharField(
        label='Ценностные предложения',
        required=True,
        widget=forms.Textarea(attrs={'rows': '2'}),
        help_text='Какую проблему потребителя мы решаем?'
    )
    bm_cash_flows = forms.CharField(
        label='Потоки доходов',
        widget=forms.Textarea(attrs={'rows': '2'}),
        required=True,
        help_text='Как вы зарабатываете деньги и как еще их можно заработать с тем же продуктом и ресурсами?'
    )
    bm_main_resources = forms.CharField(
        label='Главные ресурсы',
        widget=forms.Textarea(attrs={'rows': '2'}),
        required=True,
        help_text='Какие ресурсы нужны, чтобы создать и реализовать ценностные предложения?'
    )
    bm_communication_channels = forms.CharField(
        label='Каналы коммуникации',
        widget=forms.Textarea(attrs={'rows': '2'}),
        required=True,
        help_text='Какие каналы взаимодействия с клиентами у вас есть?'
    )
    bm_customer_relations = forms.CharField(
        label='Отношения с клиентами',
        widget=forms.Textarea(attrs={'rows': '2'}),
        required=True,
        help_text='Какой клиентский сервис и отношение ждет типичный представитель целевой аудитории проекта?'
    )
    bm_key_activities = forms.CharField(
        label='Потребительские сегменты',
        widget=forms.Textarea(attrs={'rows': '2'}),
        required=True,
        help_text='Что нужно сделать, чтобы получить ценностное предложение?'
    )
    bm_key_partners = forms.CharField(
        label='Ключевые партнеры',
        widget=forms.Textarea(attrs={'rows': '2'}),
        required=True,
        help_text='Без каких контрагентов ваш бизнес будет невозможен?'
    )
    bm_cost_structure = forms.CharField(
        label='Структура издержек',
        widget=forms.Textarea(attrs={'rows': '2'}),
        required=True,
        help_text='Из каких затрат складывается создание и реализация продукта?'
    )
    revenue = forms.DecimalField(
        label='Выручка в миллионах рублей',
        required=True,
    )
    number_of_clients = forms.IntegerField(
        label='Колличество клиентов',
        required=True
    )
    team = forms.CharField(
        label='Ваша команда',
        widget=forms.Textarea(attrs={'rows': '2'}),
        required=True
    )
    desired_investments = forms.DecimalField(
        label='Желаемые инвестиции в миллионах рублей',
        required=True
    )
    investment_round = forms.CharField(
        label='Инвестиционный раунд',
        help_text= 'Pre-seed, Series A, Series B, Series C',
        required=True
    )
    investments = forms.CharField(
        label='Куда вы потратите инвестиции',
        help_text= 'Формат: маркетинг 0.4; разработка 0.3; себе 0.3',
        required=True
    )
    roadmap = forms.CharField(
        label='Роадмап',
        widget=forms.Textarea(attrs={'rows': '2'}),
        required=True
    )
    contact_information = forms.CharField(
        label='Контактная информация',
        widget=forms.Textarea(attrs={'rows': '2'}),
        required=True
    )

pitch_deck/generator/views.py
import os

from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings

from .forms import PitchDeckForm
from .generator import PitchDeckGenerator
from .parsers import get_tam_sam_som, initialise_driver


def index(request):
    template = 'index.html'
    return render(request, template)


def pitch_deck(request):
    template = 'form.html'
    if request.method == 'POST':
        form = PitchDeckForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            # driver = initialise_driver()
            # tam, sam, som, conc = get_tam_sam_som(driver, region="Москва", okved="611000", market="Gaming", our_part=0.05)
            # driver.quit()
            # print(tam, sam, som, conc)


            # print(form.cleaned_data.get('revenue'))

            timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
            title = f'presentation-{timestamp}'
            file_path = os.path.join('presentations', 'generated', f'{title}.pptx')

            generator = PitchDeckGenerator(
                content=form.cleaned_data,
                template_name='shablon',
                logo_path=os.path.join('presentations', 'logos', 'logo.png'),
                presentation_path=file_path
            )
            generator.create_pptx()

            with open(file_path, 'rb') as file:
                pitch_deck = file.read()

            response = HttpResponse(
                pitch_deck,
                content_type='application/vnd.openxmlformats-officedocument.presentationml.presentation'
            )
            response['Content-Disposition'] = f'attachment; filename="{title}.pptx"'
            return response
    else:
        form = PitchDeckForm()
    return render(request, template, {'form': form})

pitch_deck/templates/form.html
<!DOCTYPE html>
{% load static %}
{% load user_filters %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pitch Deck Генератор</title>
    <link rel="icon" href="{% static "img/logo.png" %}" type="image">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style/index.css' %}">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top" style="height: 100px;">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="{% static "/img/logo.png" %}"
                     height="70"
                     class="d-inline-block align-top"
                     alt="">
              </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="btn btn-primary btn-lg radius brand-color" href="{% url 'generator:index' %}">На главную</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<section id="forms" class="">
    <div class="container">
        <h1 class="text-center">Заполните поля для генерации Pitch Deck</h1>
            <div class="mt-4">
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">{{ error|escape }}</div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">{{ error|escape }}</div>
                    {% endfor %}
                {% endif %}

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group row my-3">
                            <label class="h4" for="{{ field.id_for_label }}">
                                {{ field.label }}
                                {% if field.field.required %}
                                    <span class="required text-danger">*</span>
                                {% endif %}
                            </label>
                            {{ field|addclass:'form-control' }}
                            {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="py-5 form-group d-flex justify-content-center align-items-center">
                        <button type="submit" class="btn btn-primary btn-lg w-75 radius">Сгенерировать Pitch Deck</button>
                    </div>
                </form>
            </div>
    </div>
</section>


    {% comment %} <section id="forms" class="py-5">
        <div class="container mt-5">
            <h1 class="text-center">Заполните поля для генерации Pitch Deck</h1>
            <div class="mt-4">
                <form method="POST">
                  {% csrf_token %}
                    <div class="form-group">
                      <label class="h4" for="question">Вопрос</label>
                      <textarea class="form-control" id="exampleFormControlTextarea1" name='question' rows="2">{{ form.question.value }}</textarea>
                    </div>
                    <div class="form-group">
                        <label class="h4" for='context'>Контекст</label>
                        <textarea class="form-control" id="exampleFormControlTextarea2" name='context' rows="7">{{ form.context.value}}</textarea>
                      </div>
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary btn-lg">Задать вопрос</button>
                    </div>
                </form>
            </div>
            {% comment %} <div class="mt-4">
                  <div class="form-group">
                    <label class="h4" for='answer'>Ответ модели</label>
                    <textarea class="form-control" name="answer" rows="3" readonly>{{ answer }}</textarea>
                  </div>
            </div> 
        </div>
    </section>{% endcomment %}

    <footer class="d-flex justify-content-center align-items-center text-primary bg-white">
        <p class="text-primary fw-bold">&copy; 2023 DeviA'nts. All rights reserved.</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

pitch_deck/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная</title>
    <link rel="icon" href="{% static "img/logo.png" %}" type="image">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style/index.css' %}">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top" style="height: 100px;">
        <div class="container">
            <a class="navbar-brand" href="#first-block">
                <img src="{% static "/img/logo.png" %}"
                     height="70"
                     class="d-inline-block align-top"
                     alt="">
              </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="mx-4 btn btn-primary btn-lg radius brand-color deck-faq-button" href="#pitch-deck-faq">Что такое Pitch Deck</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-primary btn-lg radius brand-color" href="{% url 'generator:pitch-deck' %}">Сгенерировать Pitch-Deck</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>


    <div class="jumbotron jumbotron-fluid text-center" id="first-block">
        <div class="container">
            <h1 class="display-4">Сделайте первый шаг к успешному будущему вашего проекта!</h1>
            <p class="lead">Создайте впечатляющий Pitch Deck, который отразит все преимущества и потенциал вашего стартапа.</p>
            <a href="{% url 'generator:pitch-deck' %}" class="btn btn-primary btn-lg radius brand-color">Сгенерировать Pitch-Deck</a>
        </div>
    </div>

    <section id="about" class="py-5">
        <div class="container brand-color radius">
            <div class="row">
                <div class="col-md-6 text-white">
                    <h2 class="pb-3 padding">O нас</h2>
                    <p class="fs-3 padding">
                        АКСЕЛЕРАТОР ВОЗМОЖНОСТЕЙ — организатор технологических и инвестиционных мероприятий, оператор инновационной деятельности ИНТЦ МГУ «Воробьевы горы»
                    </p>
                </div>
                <div class="col-md-6 padding">
                    <img src="{% static "img/about.png" %}" alt="About Us" class="img-fluid radius">
                </div>
            </div>
        </div>
    </section>

    <section id="pitch-deck-faq" class="py-6">
        <div class="container brand-color-lite radius">
            <div class="row">
                <div class="col-md text-white text-center">
                    <h1 class="pb-3 padding">Что такое Pitch Deck?</h1>
                    <p class="fs-3 padding">
                        Pitch-Deck представляет собой презентацию-тизер проекта/компании для инвесторов, партнеров,
                        журналистов и других заинтересованных лиц. Цель презентации - привлечение дополнительного
                        финансирования (инвестиций)
                    </p>
                </div>
            </div>
        </div>
    </section>

    {% comment %} <section id="pitch-deck-faq" class="py-6">
        <div class="container brand-color-lite radius">
            <div class="row">
                <div class="col-md text-white text-center">
                    <h1 class="pb-3 padding">Что такое Pitch Deck?</h1>
                    <p class="fs-3 padding">
                        Pitch-Deck представляет собой презентацию-тизер проекта/компании для инвесторов, партнеров,
                        журналистов и других заинтересованных лиц. Цель презентации - привлечение дополнительного
                        финансирования (инвестиций)
                    </p>
                </div>
            </div>
        </div>
    </section> {% endcomment %}

    <section id="problems" class="py-5">
        <div class="container brand-color-lite radius">
            <h1 class="pb-3 padding text-center text-white">Какие проблемы решает генератор Pitch Deck</h1>
            <div class="row">
                <div class="col-md-4 padding-for-problems">
                    <div class="p-4 radius brand-color">
                        <h2 class="text-white fw-bold">Недостаток экспертизы</h2>
                        <p class="fs-5 text-white">Проблемой для стартапов является недостаток экспертизы для проведения необходимых исследований и
                            корректного отражения их результатов в Pitch Deck. Не всегда у стартапов есть нужные знания в области
                            маркетинга, финансов и анализа рынка, что затрудняет создание убедительной и информативной
                            презентации для привлечения инвестиций.
                            Таким образом, основателям компании зачастую приходится обращаться к консалтинговым компаниям,
                            сопровождающим сделку и берущим подготовку документов на себя.</p>
                    </div>
                </div>
                <div class="col-md-4 padding-for-problems">
                    <div class="p-4 radius brand-color">
                        <h2 class="text-white fw-bold">Недостаток времени</h2>
                        <p class="fs-5 text-white">Молодым компаниям для привлечения инвестиций требуется подготовить целый пакет документов, одним
                            из которых является Pitch Deck. Особенностью стартапов является сравнительного молодая и небольшая
                            команда, у которой чисто физически не хватает времени на разработку инвестиционных материалов, ведь
                            они полностью погружены в процесс разработки и улучшения продукта или сервиса.</p>
                    </div>
                </div>
                <div class="col-md-4 padding-for-problems">
                    <div class="p-4 radius brand-color">
                        <h2 class="text-white fw-bold">Недостаток средств</h2>
                        <p class="fs-5 text-white">Для многих стартапов ограниченные финансы создают преграду при разработке качественного Pitch Deck.
                            Отсутствие достаточных средств для найма профессиональных консультантов, дизайнеров и копирайтеров,
                            а также для проведения исследований рынка, может привести к созданию менее привлекательной и
                            малоинформативной презентации, что затрудняет привлечение инвестиций.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <footer class="d-flex justify-content-center align-items-center text-primary bg-white">
        <p class="text-primary fw-bold">&copy; 2023 DeviA'nts. All rights reserved.</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

pitch_deck/templates/test.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pitch Deck Генератор</title>
    <link rel="icon" href="{% static "img/logo.png" %}" type="image">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style/index.css' %}">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top" style="height: 100px;">
        <div class="container">
            <a class="navbar-brand" href="#first-block">
                <img src="{% static "/img/logo.png" %}"
                     height="70"
                     class="d-inline-block align-top"
                     alt="">
              </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#pitch-deck-faq">Что такое Pitch Deck</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Сгенерировать Pitch-Deck</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>


    <div class="jumbotron jumbotron-fluid text-center" id="first-block">
        <div class="container">
            <h1 class="display-4">Сделайте первый шаг к успешному будущему вашего проекта!</h1>
            <p class="lead">Создайте впечатляющий Pitch Deck, который отразит все преимущества и потенциал вашего стартапа.</p>
            <a href="#forms" class="btn btn-primary btn-lg radius brand-color">Сгенерировать Pitch-Deck</a>
        </div>
    </div>

    <section id="about" class="py-5">
        <div class="container brand-color radius">
            <div class="row">
                <div class="col-md-6 text-white">
                    <h2 class="pb-3 padding">O нас</h2>
                    <p class="fs-3 padding">
                        АКСЕЛЕРАТОР ВОЗМОЖНОСТЕЙ — организатор технологических и инвестиционных мероприятий, оператор инновационной деятельности ИНТЦ МГУ «Воробьевы горы»
                    </p>
                </div>
                <div class="col-md-6 padding">
                    <img src="{% static "img/about.png" %}" alt="About Us" class="img-fluid radius">
                </div>
            </div>
        </div>
    </section>

    <section id="pitch-deck-faq" class="py-6">
        <div class="container brand-color-lite radius">
            <div class="row">
                <div class="col-md text-white text-center">
                    <h1 class="pb-3 padding">Что такое Pitch Deck?</h1>
                    <p class="fs-3 padding">
                        Pitch-Deck представляет собой презентацию-тизер проекта/компании для инвесторов, партнеров,
                        журналистов и других заинтересованных лиц. Цель презентации - привлечение дополнительного
                        финансирования (инвестиций)
                    </p>
                </div>
            </div>
        </div>
    </section>

    {% comment %} <section id="pitch-deck-faq" class="py-6">
        <div class="container brand-color-lite radius">
            <div class="row">
                <div class="col-md text-white text-center">
                    <h1 class="pb-3 padding">Что такое Pitch Deck?</h1>
                    <p class="fs-3 padding">
                        Pitch-Deck представляет собой презентацию-тизер проекта/компании для инвесторов, партнеров,
                        журналистов и других заинтересованных лиц. Цель презентации - привлечение дополнительного
                        финансирования (инвестиций)
                    </p>
                </div>
            </div>
        </div>
    </section> {% endcomment %}

    <section id="problems" class="py-5">
        <div class="container brand-color-lite radius">
            <h1 class="pb-3 padding text-center text-white">Какие проблемы решает генератор Pitch Deck</h1>
            <div class="row">
                <div class="col-md-4 padding-for-problems">
                    <div class="p-4 radius brand-color">
                        <h2 class="text-white fw-bold">Недостаток экспертизы</h2>
                        <p class="fs-5 text-white">Проблемой для стартапов является недостаток экспертизы для проведения необходимых исследований и
                            корректного отражения их результатов в Pitch Deck. Не всегда у стартапов есть нужные знания в области
                            маркетинга, финансов и анализа рынка, что затрудняет создание убедительной и информативной
                            презентации для привлечения инвестиций.
                            Таким образом, основателям компании зачастую приходится обращаться к консалтинговым компаниям,
                            сопровождающим сделку и берущим подготовку документов на себя.</p>
                    </div>
                </div>
                <div class="col-md-4 padding-for-problems">
                    <div class="p-4 radius brand-color">
                        <h2 class="text-white fw-bold">Недостаток времени</h2>
                        <p class="fs-5 text-white">Молодым компаниям для привлечения инвестиций требуется подготовить целый пакет документов, одним
                            из которых является Pitch Deck. Особенностью стартапов является сравнительного молодая и небольшая
                            команда, у которой чисто физически не хватает времени на разработку инвестиционных материалов, ведь
                            они полностью погружены в процесс разработки и улучшения продукта или сервиса.</p>
                    </div>
                </div>
                <div class="col-md-4 padding-for-problems">
                    <div class="p-4 radius brand-color">
                        <h2 class="text-white fw-bold">Недостаток средств</h2>
                        <p class="fs-5 text-white">Для многих стартапов ограниченные финансы создают преграду при разработке качественного Pitch Deck.
                            Отсутствие достаточных средств для найма профессиональных консультантов, дизайнеров и копирайтеров,
                            а также для проведения исследований рынка, может привести к созданию менее привлекательной и
                            малоинформативной презентации, что затрудняет привлечение инвестиций.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>


    {% comment %} <section id="forms" class="py-5">
        <div class="container mt-5">
            <h1 class="text-center">Задать вопрос модели</h1>
            <div class="mt-4">
                <form method="POST">
                  {% csrf_token %}
                    <div class="form-group">
                      <label class="h4" for="question">Вопрос</label>
                      <textarea class="form-control" id="exampleFormControlTextarea1" name='question' rows="2">{{ form.question.value }}</textarea>
                    </div>
                    <div class="form-group">
                        <label class="h4" for='context'>Контекст</label>
                        <textarea class="form-control" id="exampleFormControlTextarea2" name='context' rows="7">{{ form.context.value}}</textarea>
                      </div>
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary btn-lg">Задать вопрос</button>
                    </div>
                </form>
            </div>
            <div class="mt-4">
                  <div class="form-group">
                    <label class="h4" for='answer'>Ответ модели</label>
                    <textarea class="form-control" name="answer" rows="3" readonly>{{ answer }}</textarea>
                  </div>
            </div>
        </div>
    </section> {% endcomment %}
    <footer class="text-white text-center py-3 brand-color">
        <p>&copy; 2023 DeviA'nts. All rights reserved.</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>